export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const REQUEST_QUESTIONS_PENDING = 'REQUEST_QUESTIONS_PENDING';
export const REQUEST_QUESTIONS_SUCCESS = 'REQUEST_QUESTIONS_SUCCESS';
export const REQUEST_QUESTIONS_FAILED = 'REQUEST_QUESTIONS_FAILED';
export const ADD_ANSWER_TO_QUESTION = 'ADD_ANSWER_TO_QUESTION';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_PENDING = 'ADD_QUESTION_PENDING';
export const ADD_QUESTION_FAILED = 'ADD_QUESTION_FAILED';
