export const SET_AUTH_USER = 'SET_AUTH_USER';

export const REQUEST_USERS_PENDING = 'REQUEST_USERS_PENDING';

export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';

export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED';

export const ADD_ANSWER_TO_USER = 'ADD_ANSWER_TO_USER';

export const ADD_QUESTION_TO_USER = 'ADD_QUESTION_TO_USER';

export const SAVE_QUESTION_FAILED = 'SAVE_QUESTION_FAILED';
